function [BW,maskedRGBImage] = createMask(image,data)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder App. The colorspace and
%  minimum/maximum values for each channel of the colorspace were set in the
%  App and result in a binary mask BW and a composite image maskedRGBImage,
%  which shows the original RGB image values under the mask BW.

% Auto-generated by colorThresholder app on 24-Dec-2017
%------------------------------------------------------


% Convert RGB image to chosen color space
I = image;

% Define thresholds for channel 1 based on histogram settings
channel1Min = data{1};
channel1Max = data{2};

% Define thresholds for channel 2 based on histogram settings
channel2Min = data{3};
channel2Max = data{4};
% Define thresholds for channel 3 based on histogram settings
channel3Min = data{5};
channel3Max = data{6};

% Create mask based on chosen histogram thresholds
sliderBW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
BW = sliderBW;

% Initialize output masked image based on input image.
maskedRGBImage = image;

% Set background pixels where BW is false to zero.
maskedRGBImage(repmat(~BW,[1 1 3])) = 0;
end
